const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'
const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

export {
    ADMIN_LOGIN_REQUEST,
    ADMIN_LOGIN_SUCCESS,
    ADMIN_LOGIN_FAIL,
    ADMIN_LOGOUT
}