const BOOKINGS_LIST_REQUEST = 'BOOKINGS_LIST_REQUEST'
const BOOKINGS_LIST_REQUEST_SUCCESS = 'BOOKINGS_LIST_REQUEST_SUCCESS'
const BOOKINGS_LIST_REQUEST_FAIL = 'BOOKINGS_LIST_REQUEST_FAIL'


export {
    BOOKINGS_LIST_REQUEST,
    BOOKINGS_LIST_REQUEST_SUCCESS,
    BOOKINGS_LIST_REQUEST_FAIL
}