const BOOKINGS_LIST_REQUEST = 'BOOKINGS_LIST_REQUEST'
const BOOKINGS_LIST_REQUEST_SUCCESS = 'BOOKINGS_LIST_REQUEST_SUCCESS'
const BOOKINGS_LIST_REQUEST_FAIL = 'BOOKINGS_LIST_REQUEST_FAIL'
const BOOKING_UPDATE = 'BOOKING_UPDATE'
const BOOKING_DELETE = 'BOOKING_DELETE'


export {
    BOOKINGS_LIST_REQUEST,
    BOOKINGS_LIST_REQUEST_SUCCESS,
    BOOKINGS_LIST_REQUEST_FAIL,
    BOOKING_UPDATE,
    BOOKING_DELETE
}