const BOOKINGS_LIST_REQUEST = 'BOOKINGS_LIST_REQUEST'
const BOOKINGS_LIST_REQUEST_SUCCESS = 'BOOKINGS_LIST_REQUEST_SUCCESS'
const BOOKINGS_LIST_REQUEST_FAIL = 'BOOKINGS_LIST_REQUEST_FAIL'
const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS'
const BOOKING_UPDATE_SUCCESS = 'BOOKING_UPDATE_SUCCESS'
const BOOKING_DELETE_SUCCESS = 'BOOKING_DELETE_SUCCESS'


export {
    BOOKINGS_LIST_REQUEST,
    BOOKINGS_LIST_REQUEST_SUCCESS,
    BOOKINGS_LIST_REQUEST_FAIL,
    BOOKING_CREATE_SUCCESS,
    BOOKING_UPDATE_SUCCESS,
    BOOKING_DELETE_SUCCESS
}