const PROPERTIES_LIST_REQUEST = 'PROPERTIES_LIST_REQUEST'
const PROPERTIES_LIST_REQUEST_SUCCESS = 'PROPERTIES_LIST_REQUEST_SUCCESS'
const PROPERTIES_LIST_REQUEST_FAIL = 'PROPERTIES_LIST_REQUEST_FAIL'
const PROPERTIES_SEARCH = 'PROPERTY_SEARCH'


export {
    PROPERTIES_LIST_REQUEST,
    PROPERTIES_LIST_REQUEST_SUCCESS,
    PROPERTIES_LIST_REQUEST_FAIL,
    PROPERTIES_SEARCH
}