const PROPERTIES_LIST_REQUEST = 'PROPERTIES_LIST_REQUEST'
const PROPERTIES_LIST_REQUEST_SUCCESS = 'PROPERTIES_LIST_REQUEST_SUCCESS'
const PROPERTIES_LIST_REQUEST_FAIL = 'PROPERTIES_LIST_REQUEST_FAIL'


export {
    PROPERTIES_LIST_REQUEST,
    PROPERTIES_LIST_REQUEST_SUCCESS,
    PROPERTIES_LIST_REQUEST_FAIL
}