const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
const USER_LOGOUT = 'USER_LOGOUT'
const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
const USER_SIGNUP_FAIL = 'USER_SIGNUP_SUCCESS'

const USERS_LIST_REQUEST = 'USERS_LIST_REQUEST'


export {
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAIL,
    USER_LOGOUT,
    USER_SIGNUP_SUCCESS,
    USER_SIGNUP_FAIL,
    USERS_LIST_REQUEST
}