const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
const USER_LOGOUT = 'USER_LOGOUT'

const PROPERTIES_LIST_REQUEST_SUCCESS = 'PROPERTIES_LIST_REQUEST_SUCCESS'
const PROPERTIES_LIST_REQUEST_FAIL = 'PROPERTIES_LIST_REQUEST_FAIL'

export {
    USER_LOGIN_REQUEST,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAIL,
    USER_LOGOUT,
    PROPERTIES_LIST_REQUEST_SUCCESS,
    PROPERTIES_LIST_REQUEST_FAIL
}