export const PROPERTIES_LIST_REQUEST = 'PROPERTIES_LIST_REQUEST'
export const PROPERTIES_LIST_REQUEST_SUCCESS = 'PROPERTIES_LIST_REQUEST_SUCCESS'
export const PROPERTIES_LIST_REQUEST_FAIL = 'PROPERTIES_LIST_REQUEST_FAIL'
